'use strict';

export const PLAYLIST_COMPONENT_TITLE = 'Playlist';
export const PLAYLIST_COMPONENT_NO_PLAYLIST_CONTENT = 'No playlist was found!\nHead to your youtube account and add some music!';
export const PLAYLIST_ITEM_COMPONENT_NO_CONTENT = 'No videos was found in this playlist!';
export const PLAYLIST_VIDEO_COMPONENT_TITLE = 'Preview';
export const PLAYLIST_VIDEO_COMPONENT_NOT_AVAILABLE = 'This track can not be downloaded, it might be because of it\'s length or Youtube error.';
export const INITIAL_COMPONENT_TITLE = 'Youtube Music';
export const INITIAL_COMPONENT_MESSAGE = 'You must sign in with google account so we can get your playlist from youtube and import them here.';
export const INITIAL_COMPONENT_AUTHORIZE_ACTION = 'Continue';
export const AUTHORIZATION_COMPONENT_TITLE = 'Authorization';
export const PLAYER_LIST_COMPONENT_TITLE = 'Player';
export const PLAYER_LIST_COMPONENT_NO_CONTENT = 'No music is added in your library! Login with your youtube account and add some fun!';
export const VIDEO_DOWNLOADED = 'Downloaded';
export const VIDEO_DOWNLOAD = 'Download';
export const VIDEO_DOWNLOADING = e => `Downloading ${e}%`;
export const LOGOUT = 'Logout';
export const PLAYER = 'Player';
export const LOGIN = 'Login';
export const BACK = 'Back';
export const DELETE = 'Delete';
export const CANCEL = 'Cancel';
export const OPEN_IN_YOUTUBE = 'Open In Youtube';